baseURL = "https://dgoppenheimer.github.io/pymol-notes/"
languageCode = "en-us"
title = "PyMOL Notes"
theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
    custom_css = ["css/custom.css"]
    disableInlineCopyToClipBoard = true 
